export default {
  name: 'Enter Name',
  errorName: 'Please enter a valid name',
  errorAge: 'Please enter a valid age',
  save: 'Add',
  edit: 'Edit Children',
  add: 'Add Children',
  title: 'Credit',
  dashboardTitle: 'Children',
  backPress: 'hardwareBackPress',
  descriptionTitle: 'Description: ',
  ageTitle: 'Age: ',
  emptyList: 'Add your children by clicking on the + button',
  age: 'Enter Age',
  deleteTitle: 'Do you want to delete?',
  yes: 'Yes',
  no: 'No',
  addCardTitle: 'Add Card',
  viewCardTitle: 'View card',
  register: 'Register',
  email: 'Enter Email',
  errorEmail: 'Please Enter a valid email address',
  delete: 'Delete',
  Name: 'Name: ',
  details: 'Details',
  editMonthlyLimit: 'Edit Monthly Limit',
  update: 'Update',
  productTitle: 'Products',
};
